image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: open-browser
  - port: 3333
    onOpen: open-preview

tasks:
  - init: echo 'starting postgresql' # runs during prebuild
    command: pg_start
